// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKSE_N_63Yv8BBP7axecMDaGsSSQdQdVk',
    appId: '1:146586958778:web:8309f4a48e9ade9e4fbb83',
    messagingSenderId: '146586958778',
    projectId: 'bardbeats-8f621',
    authDomain: 'bardbeats-8f621.firebaseapp.com',
    storageBucket: 'bardbeats-8f621.appspot.com',
    measurementId: 'G-YM4VWGX9F9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuDX_6LablKHROkckfMOdAlL7MT00B-gE',
    appId: '1:146586958778:android:3ccf99c7eaca1b454fbb83',
    messagingSenderId: '146586958778',
    projectId: 'bardbeats-8f621',
    storageBucket: 'bardbeats-8f621.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3GcZBfQWTFRRVhrKRbMlAWNwY--Yt0A4',
    appId: '1:146586958778:ios:872b7e72ff92b37f4fbb83',
    messagingSenderId: '146586958778',
    projectId: 'bardbeats-8f621',
    storageBucket: 'bardbeats-8f621.appspot.com',
    iosBundleId: 'com.example.bardbeatsdash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3GcZBfQWTFRRVhrKRbMlAWNwY--Yt0A4',
    appId: '1:146586958778:ios:c1949600aabc296e4fbb83',
    messagingSenderId: '146586958778',
    projectId: 'bardbeats-8f621',
    storageBucket: 'bardbeats-8f621.appspot.com',
    iosBundleId: 'com.example.bardbeatsdash.RunnerTests',
  );
}
